spring.application.name=LearningPlatformValidation

spring.datasource.url=jdbc:oracle:thin:@en3l01n72mb5qvnz_tp?TNS_ADMIN=C:/proyectos/LearningPlatformValidation/LearningPlatformValidation/src/main/resources/wallet
spring.datasource.username=ADMIN
spring.datasource.password=ZxW35DW089?JS
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=*